# Generated by Django 6.0.4 on 2026-05-14 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_can_access_cash_closing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='can_access_cash_closing',
            new_name='can_access_shift_report',
        ),
    ]
