# Generated by Django 6.0.4 on 2026-05-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_can_access_cash_closing_userprofile_can_access_shift_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
