# Generated by Django 6.0.4 on 2026-06-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_tenant_id_saleitem_tenant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('gcash', 'GCash'), ('maya', 'Maya'), ('grabpay', 'GrabPay'), ('shopeepay', 'ShopeePay'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
