# Generated by Django 6.0.4 on 2026-05-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_tenant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('tenant_id', 'email')},
        ),
    ]
